---
apiVersion: v1
kind: Service
metadata:
  name: ingress-lb
spec:
  type: LoadBalancer
  selector:
    app: ingress-controller
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 81
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443